version: '3.8'

services:
  puffcoin:
    build: .
    container_name: puffcoin-node
    ports:
      - "8333:8333"
    volumes:
      - ./puffcoin.conf:/root/.puffcoin/puffcoin.conf:ro
      - puffcoin-data:/root/.puffcoin
    restart: unless-stopped
    command: ["./puffcoind", "-server", "-gen=1", "-genproclimit=4"]

volumes:
  puffcoin-data: