version: '3.8'

services:
  node1:
    build: .
    container_name: puffcoin-node1
    ports:
      - "8333:8333"   # основной порт для входящих соединений
      - "8332:8332"   # RPC порт (по желанию, можно убрать)
    volumes:
      - ./node1/puffcoin.conf:/root/.puffcoin/puffcoin.conf
      - node1-data:/root/.puffcoin
    restart: unless-stopped
    network_mode: bridge

volumes:
  node1-data:
